name: Publish to GitHub Pages

on:
  push:
    branches:
      - main  # Modify this to match your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Copy files to deployment directory
        run: |
          cp index.html dist/index.html
          cp a.zip dist/a.zip
          cp b.zip dist/b.zip
          cp c.zip dist/c.zip

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          
  permissions:
    contents: # Ensure this workflow can modify contents of the repository
      paths:
        - dist
      permissions: write
